In [1]:
import torch

In [8]:
x = torch.tensor([3],dtype=torch.float32, requires_grad=True)

In [10]:
y = 2 * x ** 2

In [11]:
y.backward()

In [12]:
x.grad

tensor([12.])

In [15]:
x1 = torch.tensor([3],dtype=torch.float32, requires_grad=True)
x2 = torch.tensor([2],dtype=torch.float32, requires_grad=True)

In [16]:
y = 2 * x1 ** 2 + 3 * x2 ** 3

In [17]:
y.backward()

In [18]:
x1.grad

tensor([12.])

In [19]:
x2.grad

tensor([36.])